### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by zach-morris** [videogame-archive/romhack-archive#2]
Your discord invite is currently invalid.
At any rate, I created a data dump a few years ago that may or may not be useful for your project.  Feel free to utilize it if you want to:
https://github.com/zach-morris/romhack_db

**Comment by videogame-archive** [comment]
Just tested, works for me: https://discord.gg/AEV88uDTeQ

**Comment by zach-morris** [comment]
Working now!
